POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username":"hoanghihi",
    "password":"hihi"
}


###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username":"henry4",
    "password":"henry"
}


###

POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer 63bec5533dde30de0221978d

{
    "title":"Node",
    "description":"Node",
    "url":"react.com",
    "status":"LEARNED"
}

###
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2JlY2MwNmQwYjEwMjEzZDc5MDg1MWYiLCJpYXQiOjE2NzM0NDg0NTR9.02k__StKlxowlvoMEqO881RqwBpAFNvkc3yIdI4Z83c


###
PUT http://localhost:5000/api/posts/6061c25ac2533d41dcae2b19
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDYxYjk1YjdkMjljZTFiMTA5YmQxZTAiLCJpYXQiOjE2MTcwMTk3ODF9.ri-nHdgZc1VQTocFLfMgF4_PhFf2TeUVqXLd8tpOkeA

{
  "title": "Vue",
  "description": "VUEEEEE",
  "url": "https://vuejs.org",
  "status": "LEARNING"
}

###

DELETE http://localhost:5000/api/posts/6061c25ac2533d41dcae2b19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDYxYjk1YjdkMjljZTFiMTA5YmQxZTAiLCJpYXQiOjE2MTcwMTk3ODF9.ri-nHdgZc1VQTocFLfMgF4_PhFf2TeUVqXLd8tpOkeA
